
GET https://api.openweathermap.org/data/2.5/find?q=London&units=metric&appid=207159a018d0b8a0f4e26b6f886e4ac7

#GET https://api.openweathermap.org/data/2.5/weather?lat=52&lon=-122.4194&units=metric&appid=207159a018d0b8a0f4e26b6f886e4ac7